
const pokemonDict = [
  {
    image: "./src/assets/Pikachu.webp", 
    answer: "Pikachu", 
    difficulty: "easy", 
    description:"When it is angered, it immediately discharges the energy stored in the pouches in its cheeks.",
    footprint: "./src/assets/Pikachu_FP.png",
    height: "1'04",
    weight: "13.2",
  },
  { 
    image: "./src/assets/Totodile.webp", 
    answer: "Totodile", 
    difficulty: "medium", 
    description:"Despite the smallness of its body, this Pokemon’s jaws are very powerful. While the Pokémon may think it is just playfully nipping, its bite has enough power to cause serious injury.",
    footprint: "./src/assets/Totodile_FP.png",
    height: "2'00",
    weight: "20.9",
  },
  {
    image: "./src/assets/Charizard.jpg", 
    answer: "Charizard", 
    difficulty: "easy" , 
    description:"It is said that this Pokemon's fire burns hotter if it has experienced harsh battles.",
    footprint: "./src/assets/Charizard_FP.png",
    height: "5'07",
    weight: "199.5",
  },
  {
    image: "./src/assets/Mew.jpg", 
    answer: "Mew", 
    difficulty: "easy" , 
    description:"When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen.",
    footprint: "./src/assets/Mew_FP.png",
    height: "1'04",
    weight: "8.8",
  },
  {
    image: "./src/assets/Weedle.webp", 
    answer: "Weedle", 
    difficulty: "easy" , 
    description:"Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.",
    footprint: "./src/assets/Weedle_FP.png",
    height: "1'00",
    weight: "7.1",
  },
  {
    image: "./src/assets/Feebas.png", 
    answer: "Feebas", 
    difficulty: "hard", 
    description:"Although unattractive and unpopular, this Pokémon’s marvelous vitality has made it a subject of research." ,
    footprint: "./src/assets/Empty_FP.png",
    height: "2'00",
    weight: "16.3",
  },
  {
    image: "./src/assets/Steelix.png", 
    answer: "Steelix", 
    difficulty: "medium", 
    description:"It is said that if an Onix lives for over 100 years, its composition changes to become diamond-like.",  
    footprint: "./src/assets/Empty_FP.png",
    height: "30'02",
    weight: "881.8",
  },
  {
    image: "./src/assets/Arceus.jpg", 
    answer: "Arceus", 
    difficulty: "hard", 
    description:"According to the legends of Sinnoh, this Pokémon emerged from an egg and shaped all there is in this world.",
    footprint: "./src/assets/Arceus_FP.png",
    height: "10'06",
    weight: "705.5",
  },
  {
    image: "./src/assets/Ditto.webp", 
    answer: "Ditto", 
    difficulty: "medium", 
    description:"Its transformation ability is perfect. However, if made to laugh, it can’t maintain its disguise.",
    footprint: "./src/assets/Empty_FP.png",
    height: "1'00",
    weight: "8.8",
  },
  {
    image: "./src/assets/Mismagius.avif", 
    answer: "Mismagius", 
    difficulty: "hard", 
    description:"Its cry sounds like an incantation. It is said the cry may rarely be imbued with happiness-giving power.", 
    footprint: "./src/assets/Empty_FP.png",
    height: "2'11",
    weight: "9.7",

  }
  ];

  export default pokemonDict;